language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jamesfelz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jamesfelz/docker-react npm run test
